const translater = {
  ESP: {
    choose_your_language: "Elige tu idioma:",
    follow_me: "Sígueme",
    icons_designed_by: "Íconos diseñados por",
    from: "de",
    home: "Home",
    all_pokemons: "Todos los Pokemons",
    about_us: "Sobre nosotros",
    contact_us: "Contáctanos",
    sign_in: "Inicia sesión",
    choose_pokemon: "Por favor, elige un Pokemón",
    loading: "Cargando...",
    stats: "Estadísticas",
    unknown: "Desconocido",
    height: "Altura",
    base_experience: "XP base",
    weight: "Peso",
    highest_stat: "Mejor en",
    description: "Descripción",
    hp: "Salud",
    defense: "Defensa",
    attack: "Ataque",
    special_attack: "Ataque Especial",
    special_defense: "Defensa Especial",
    speed: "Velocidad",
    no_moves: "Lo sentimos, no tenemos los movimientos de este pokemón.",
    moves: "Movimientos",
    name: "Nombre",
    no_page: "La página que estás buscando ha sido movida o no existe.",
    get_back: "Vamos a regresar"
  },
  ENG: {
    choose_your_language: "Choose your language:",
    follow_me: "Follow me",
    icons_designed_by: "Icons designed by",
    from: "from",
    home: "Home",
    all_pokemons: "All pokemons",
    about_us: "About us",
    contact_us: "Contact us",
    sign_in: "Sign in",
    choose_pokemon: "Please choose a pokemon",
    loading: "Loading...",
    stats: "Stats",
    unknown: "Unknown",
    height: "Height",
    base_experience: "Base XP",
    weight: "Weight",
    highest_stat: "Highest stat",
    description: "Description",
    hp: "Hp",
    defense: "Defense",
    attack: "Attack",
    special_attack: "Special Attack",
    special_defense: "Special Defense",
    speed: "Speed",
    no_moves: "Sorry, we don't have information about this pokemon.",
    moves: "Moves",
    name: "Name",
    no_page: "The page you were looking for was moved or doesn't exist.",
    get_back: "Let's get you back."
  }
}


export default translater;
